### ISSUE TITLE
Death Token

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#1]
When a Creatures reaches 0 HP it should switch to a static .webp indicating the token is "dead" or "unconcious".

- When the default idle animation is `top/***-idle_*_top.webm` it should switch to `***-dead_top.webp` in the same directory.
- When the default idle animation is `***-idle_face.webm` it should switch to `***-idle_face_still_death.webp` in the same directory.

If the HP goes back above 0 it should switch back to its former animation (`top/***-idle_*_top.webm` or `***-idle_face.webm`)

**Comment by LeRatierBretonnien** [comment]
Available in current head
