### ISSUE TITLE
Database: Add an "Installed" Filter to Items, Spells and Tokens

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#10]
I would like to have a new additional filter for `Tokens`, `Items `and `Spells` called `Show:` with the values "All", "Only installed", "Only not installed"

This way, users who only have a few packs can search the content they have access to without scrolling through everything else.

Show: All
Show: Only installed
Show: Only not installed

**Comment by LeRatierBretonnien** [comment]
Done
