### ISSUE TITLE
Beneos Search Website Item: Price <100 leds to a broken Item

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#101]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3c95210e-89cf-4439-b3fd-c2bbc1bfbe77)

I already checked the `beneos_items_database.json` there is no Item with a price < 100, so this seems like a bug.

**Comment by LeRatierBretonnien** [comment]
No, this is an explicit message indicating that there is no results
