### ISSUE TITLE
Beneos Search Website - Spell: Mourover for spell_type is not working

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#102]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/35ed75e1-69f4-4a8e-be33-450098f10540)

I have added descriptions for `spell_type` but it seems not to affect the website

![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/016e2465-b4eb-4b77-b443-a3a5d6c4d023)

**Comment by LeRatierBretonnien** [comment]
Fixed
