### ISSUE TITLE
Beneos Search Website: If you click on a filter the active filter is not shown in the search form

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#103]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/28eeb4fc-8228-42bc-b28d-b2026dda43e6)

If you click a filter, for example Spell type, it gets locked in correctly but it is not displayed in the coresponding field. The field is blank even though the filter is active as intended

**Comment by LeRatierBretonnien** [comment]
Fixed
