### ISSUE TITLE
Beneos Module - Godmode Macro to export tokenconfig

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#104]
Can you please update the macro so it is usable with the beneos_module? We need it to be able to export the tokenconfig after scaling the token.

- `game.settings.set(game.beneosTokens.moduleId, 'beneos-god-mode', true)`
- `game.settings.set(game.beneosTokens.moduleId, 'beneos-god-mode', false)`

**Comment by LeRatierBretonnien** [comment]
Fixed
