### ISSUE TITLE
Database: Battlemaps Type rename and filtering bug

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#11]
1. please rename "Kind" as "Type" in the "Maps" search form
2. The Filter for type does not seem to work 

![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/786ed7d4-1d9f-481e-886c-53dc5a1475cd)

**Comment by LeRatierBretonnien** [comment]
Fixed
