### ISSUE TITLE
Beneos Search: Tooltips out of bound

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#13]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/f2be0a9e-4a35-4092-9392-eb4a4bdee25b)

The tooltip should not be cut of by the form. If the form is the limit maybe let the tooltip appear left of the mouse?

![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/6b6e88c3-e30c-4836-aa2e-f3de0966b841)

**Comment by LeRatierBretonnien** [comment]
Fixed in CSS, will be ready for next release.
