### ISSUE TITLE
Beneos Search: Background Color Entry

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#14]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/905f6a59-e071-4492-ab63-f2c28a708264)

The background color of the entry is the same color as the background of the entire form itself. The intended Background color for (non selected) items should be: `#eaeaea`

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
