### ISSUE TITLE
Beneos Search: Icons

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#15]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/c6df7460-b0c1-4cfd-bca7-cee73b88404a)

The icons are too small. The background image is intended as a border or if the icon can not be displayed correctly. You can increase the icon as long space allows it in this icon area.

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
