### ISSUE TITLE
Beneos Search: Prominent Item Seperator

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#16]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/a14ee925-852d-4504-9a64-ff6b7180596f)

The current Item seperator is too prominent and serves no purpouse. 

Can you make it just a 3 px high line with a color of `#a8a59d` (or at least make it way more transparent or leave it out entirely as a last resort)

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
