### ISSUE TITLE
Beneos Search: Move Search form

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#18]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/0cfb05f4-cacb-45b6-be52-6656265e2c0a)

At the moment nobody can move the search form what could lead to issues with other windows getting blocked. Yes - scaling should be deactivated but a user should be able to move the forms.

**Comment by LeRatierBretonnien** [comment]
This one is very tricky, because I needed to overwrite all the basic window management to display the header. Postponed for now.

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
