### ISSUE TITLE
Moved to here: Data Base / Search Engine Update: Search Feature

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#2]
With Beneos Tokens we switch focus a bit. We go away from JUST animated tokens to tokens, spells and items. That means we offer custom dnd spells and dnd items in a high quality (not animated xD). We want to improve the Search Engine with two more Search Areas (From Battlemaps <-> Tokens TO Battlemaps <-> Tokens <-> Spells <-> Items. Please add two more databases for us to enter conent as we do for Battlemaps and Tokens.

**Features of the new Database for Items and Spells**

- We use the same structure as for tokens. That means every item and spell has its own json file in its folder. Because (as with the tokens) we want to offer different sources for content, not just Patreon. That means we also need an item and spell comepndiums build as with the tokens.
- All item folders goes to beneos_tokens_assets\_items\
- all spell folders goes to beneos_tokens_assets\_spells\

**Item Search Engine Features**
- On a Mouseover the two item cards are displayed
- If the item has a URL display the URL link as shown in the image
- Installed / Not Installed behaves as with the tokens
- The Search Engine Icon has a black stroke and a drop shadow if possible
- If the item requires Attunement display the attunement field, otherwise do not display it.
-You can drag and drop an Item into your character sheet or Item tab in Foundry from within the search result

**Spell Search Engine Features**
- On a Mouseover the two item cards are displayed
- If the item has a URL display the URL link as shown in the image
- Installed / Not Installed behaves as with the tokens
- The Search Engine Icon has a black stroke and a drop shadow if possible
- If the item requires concnetration display ithe concentration field, otherwise do not display it.
- You can drag and drop a spell into your character sheet from within the search result

![image](https://github.com/BeneosBattlemaps/BeneosTokens/assets/93905181/de0c78a0-8bed-4e8f-9b00-e3a119c84686)

**Comment by LeRatierBretonnien** [comment]
First search implementation is available.
Drag&Drop and mousever are missing, see questions in Discord

**Comment by LeRatierBretonnien** [comment]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/1085008/34d3c4ff-b6c3-464e-871a-ce07072e880e)

**Comment by LeRatierBretonnien** [comment]
Search + card mouseover implemented.
Still missing : drag&drop

**Comment by LeRatierBretonnien** [comment]
Drag&Drop implemented, ticket closed.
