### ISSUE TITLE
Beneos Search: Scrollable results box too big

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#20]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/a7e25026-764b-4b99-bf7f-3a224a676152)

I know the other search forms are not finished yet. This is just in case it might get missed. The search results are scrolling out of the form destroying the impression of a working interface.

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
