### ISSUE TITLE
Beneos Search Spells: Tag box not alligned center vertically

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#21]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/b696a3bd-3260-4bf4-bd8c-a245ca1631f9)

For Beneos Spells the Tag box is not aligned vertically (as with the items where it is correct aligned already).
Info: Keep in mind https://github.com/BeneosBattlemaps/beneos_module/issues/19 this issue should apply also with spells

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
