### ISSUE TITLE
Beneos Search Tokens:

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#22]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/25dc4141-5037-4db4-b542-1b227864673f)

The round Icon for Beneos Tokens is a bit too big. I will overwrite the icons with a square version soon. Keep it as with Beneos Icons or Spells (They will be the same aspect ratio soon)

**Comment by LeRatierBretonnien** [comment]
Invalid, token interface not functionnal
