### ISSUE TITLE
Beneos Search - Tooltip out of bound

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#23]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/19e257bf-161b-4288-8add-d86b1d4aeca4)
****

The tooltip for tokens (maybe others too) reches out of the bounds

**Comment by LeRatierBretonnien** [comment]
Invalid, unable to reproduce. All tooltips are wrapping properly here.
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/1085008/6e1dec74-2970-4337-897e-f0158a2b3559)
Please check with the real browser, not the Foundry APP.
