### ISSUE TITLE
Beneos Search: Multiple Instances

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#25]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3e058587-d9f0-421f-a126-a6aef396787c)

It is possible to create multiple instances when clicking on the search button multiple times

**Comment by LeRatierBretonnien** [comment]
This is possible, but a whole project in itsel. I propose to postpone it, because it will cost.

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
