### ISSUE TITLE
Beneos Search: Right Button Vertival Alignment

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#26]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/02635953-2d39-4f77-9a0e-dcc1f31689f6)

Can you make the right buttons alinged center vertically? they are the only boxes that are aligned this way.

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
