### ISSUE TITLE
Beneos Search: Content reaches out of the form

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#27]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/f1d4286b-da67-4f94-b741-a7011fefa6b7)

The content reaches out of the form at the bottom - but it might have something to do with the misplaced title bar pushing all content below. I added this ticket for completion

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
