### ISSUE TITLE
Beneos Search: Bigger Map Icons

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#28]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/2e1ced72-0d33-4585-830e-eca68dfc2d95)

You can use the entire space of the square Icon area (as you already do with items and spells).

![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/a1d6efa6-70d3-4c3b-83ab-b6c79b16d25f)

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
