### ISSUE TITLE
Beneos Search: Filter Form Link and Icon Alignment

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#34]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/c75824db-2a5a-423f-b1e8-62d1f8d96bb7)

- Text and Icon should be aligned center vertically
- Between Icons and text should be a small gap

As previewed in the image

**Comment by LeRatierBretonnien** [comment]
Sorry, I do not see and differences in the picture above.
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/1085008/c80003a2-a828-414c-9955-98760a94881c)

It looks correct, so I don't understand what needs to be modified

**Comment by LeRatierBretonnien** [comment]
Fixed in latest release
