### ISSUE TITLE
Beneos Search: Battlemaps has token results in its list when using the text search

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#36]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/a594a38f-ea4a-42d8-884e-e7f65e13e4fd)

Note: Ignore the missing images. I am in the process of fixing them and they do not have anything to do with this error

**Comment by LeRatierBretonnien** [comment]
Fixed
