### ISSUE TITLE
Moved: Data Base / Search Engine Update: Data Structure

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#4]
With Beneos Tokens we switch focus a bit. We go away from JUST animated tokens to tokens, spells and items. That means we offer custom dnd spells and dnd items in a high quality (not animated xD). We want to improve the Search Engine with two more Search Areas (From Battlemaps <-> Tokens TO Battlemaps <-> Tokens <-> Spells <-> Items. Please add two more databases for us to enter conent as we do for Battlemaps and Tokens.

**Spell**

- Level `(Select field - String) | Examples: "1st Level", "2nd Level", "3rd Level",...
- School `(Select field - String) | Examples: "Abjuration Spell", "Necromancy Spell", "Evocation Spell", ....`
- Casting Time `(Select field - String) | Examples: "Action", "Bonus Action", "Reaction"`
- Concentration `(Checkbox - Boolean) | Examples: Yes, No`
- Spell Type `(Select field - String) | Examples: "Support", "Offensive", "Heal", ....`
- Classes `(Select field - String): "Wizard", "Bard", "Warlock", ...`

This will only gets displayed on the result but is not part of the search inputs.
- Spell Components | String "Verbal", "Somatic",
- Short Description | String "This item is super coool bla bla bla..."

Every Item has 3 Images: The Item Icon and a bigger Card Version with two sides front and back (Like on a trading card game)

**Items**
- Rarity `(Select field - String) | Examples: "Epic", "Legendary", "Wondrous", ....`
- Attunement `(Checkbox - Boolean) | Examples: Yes, No`
- Origin `(Select field - String) | Examples: "Dwarven Forged", "Elemental Infused", ....`
- Type  `(Select field - String) | Examples: "Trinket", "Weapon", "Armors", "Consumable", "Clothing"`
- Tier `(Select field - Integer) | Examples: 1,2,3,4`
- Price `(Select field - String) | This should have a logic to build price cluster and not display every single different price tag. the cluster should be (in gold) "<1000 Gold, <5000 Gold, < 10.000 Gold, >10.000 Gold

This will only gets displayed on the result but is not part of the search inputs.
- Short Description | String "This item is super coool bla bla bla..."

Every Spell has 3 Images: The Item Icon and a bigger Card Version with two sides front and back (Like on a trading card game)

**Comment by BeneosBattlemaps** [comment]
UPDATE: I've ataches an example with 3 different spells and 3 different items. all are 100% finished and polished including the correct folder structure, icons and paths as well as the json actor export from Foundry containing the actor data for the items and spells.

Because we consolidate beneos tokens into the "beneos" module (with the intention to work on beneos battlemaps there as well in the future) here is a screenshot of the final folder structure (also added to the attached beneos_assets.zip)

![image](https://github.com/BeneosBattlemaps/BeneosTokens/assets/93905181/12551cf4-c670-4de1-b912-06109e96b779)


**NOTE:** All Items and Spells have so called spell cards and item cards as part of their item description. They are just webp images that are also displayed in the search results. All items have two individual cards (front and back side) where the spells only have one individual side (front) and the back is the same for all. Beause all spell card back sides are the same all share the same file to prevent redundancy. The path to all spell card back side is: beneos_assets\beneos_spells\spell_card_back.webp

Here is an example of an Item card
![image](https://github.com/BeneosBattlemaps/BeneosTokens/assets/93905181/7df1b022-d887-4e60-b8c9-9bac9ab61454)
  
  
[beneos_assets.zip](https://github.com/BeneosBattlemaps/BeneosTokens/files/11934737/beneos_assets.zip)

**Comment by BeneosBattlemaps** [comment]
I have attached: 
- beneos_spells_database.json
- beneos_items_database.json

With 3 examples each in the data structure you provided. Since there is no older structure yet (I've updated the old search engine and had no thumbnails folder) I also attached the icons here for you to place them in the correct folder.

[_database.jsons.zip](https://github.com/BeneosBattlemaps/beneos_module/files/12138341/_database.jsons.zip)
[item_icons.zip](https://github.com/BeneosBattlemaps/beneos_module/files/12138346/item_icons.zip)
[spell_icons.zip](https://github.com/BeneosBattlemaps/beneos_module/files/12138348/spell_icons.zip)

**Comment by LeRatierBretonnien** [comment]
Compendium building +search data managed in ticket #2 so closing this one.
The JSON database are available in the beneos-database.
