### ISSUE TITLE
Beneos Search: Update Title Bar

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#40]
Just replace the current title bar with this one. The idea was to have a different for every different Search Area, this is the reason the current one hast "items" in title. We should just stick with a generic one I attached below

[result_form_title_item.zip](https://github.com/BeneosBattlemaps/beneos_module/files/12643723/result_form_title_item.zip)

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
