### ISSUE TITLE
Beneos Search: Battlemaps - non 16:9 Battlemap resolutions

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#42]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/55ed185b-8d0e-4e1e-ba5a-894c69826901)

As mentioned in the requirements, there are maps that are not 16:9. (Sceneries are always 16:9 though). At the moment non-16:9 maps are stretched to match 16:9.

Keep the height but make the width dynamically so the aspect ratio is always correct and the image display in the best way possible.

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
