### ISSUE TITLE
Beneos Module Settings: "Enable Automatic Animations" is not needed anymore (I think)

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#46]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/7b5e2188-ba55-4983-875e-9362107f460a)

since we deleted animation switching I think this setting is not needed anymore, right?

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
