### ISSUE TITLE
Beneos Search: New Button to rebuild compendiums directly in the search form

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#47]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/dbbd3eed-0bb3-4a90-a4ea-d3c5128808f3)

Can you please add the same button you added to the Beneos Module Settings to rebuild compendiums here in the search form? The goal is to make it fast and convenient, as well as to educate Patrons that it is necessary to update the compendiums every time they add something new (Weekly Basis for Token).

**Button Text**: "Import New Content"
**Mouseover Text**: "Searches >beneos_assets< and import newly added content.

**Comment by LeRatierBretonnien** [comment]
Added in next release
