### ISSUE TITLE
Beneos Search Website: 2 - Reduce Vertical Space between search form and result form

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#51]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/8bc2ea57-c3b5-4ca9-bc26-668991f611ba)

- **2** Our goal is to create enough space to make a forth Item visible so we move the search form a top to the search form

**Comment by LeRatierBretonnien** [comment]
Five rows is not feasible without huge rework
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/1085008/6310a92b-c591-466c-acdb-a014e281d446)

**Comment by LeRatierBretonnien** [comment]
View of a browser with links, menu and buttons : 
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/1085008/2c7b160e-1e56-408c-b1c2-468b39355a5d)
