### ISSUE TITLE
Beneos Search Website: 3 - Equilize the width of the search form to match the result form

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#52]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/080abeb1-2ed0-4144-8b46-62d5e5b7c3d2)

- **3** At the moment, the search form is too wide. There should be more than enough space to make both (search and results) equal width

**Comment by LeRatierBretonnien** [comment]
Fixed
