### ISSUE TITLE
Beneos Search Website Tokens: 9 - The Icon is a bit too small

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#58]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3918e601-53c7-45e5-90a4-3f4b4d3d010c)

- **9** It looks like the icon is not scaled correctly so a small border of the image below appears

**Comment by LeRatierBretonnien** [comment]
Fixed
