### ISSUE TITLE
Beneos Search Website Battlemaps: 10 - Preview image Aspect Ratio is wrong

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#59]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/c8f7dd87-0f8f-4567-80b8-51d5663898c5)

10 - If you hover over a battlemap the preview images of the battlemap and the scenery is not scaled correctly. The Sceneery is Always 16:9 and the battlemap must be build dynamically since the aspect ratio can vary (for example 4300x7000 or 3000x1000 etc)

**Comment by LeRatierBretonnien** [comment]
Difficult to handle, postponing

**Comment by LeRatierBretonnien** [comment]
Should be OK now
