### ISSUE TITLE
Beneos Search Website Battlemaps: 11 - "Fitting Scenery" or "Fitting Battlemaps" Link can be removed

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#60]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3560150f-6782-49cb-a271-dc3fda54bb84)

You can remove these not needed links because the images are already displayed on mouseover

**Comment by LeRatierBretonnien** [comment]
Fixed
