### ISSUE TITLE
Beneos Search Website Items: 14 - implicid price filter (For both website and module)

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#62]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/ae4c88ea-c146-4657-aace-08b9de876aa1)

14 - We will have a lot of items with different prices. It makes no sense to **filter** every absolute value. Please add filter "areas" `<100g`, `< 1000g`, `<5000g`, `<15.000g` `>15.000g`
Also please add points to make the number more readable. for example 13.500 instead of 13500

**Comment by LeRatierBretonnien** [comment]
OK, will take more time, need specific code

**Comment by LeRatierBretonnien** [comment]
Fixed
