### ISSUE TITLE
Beneos Search Website: 15 - Global Text Search Visual Adjustments

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#63]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/34c08288-1c3c-45a5-b1f3-18151cbb7ddd)

A Please make the input cursor aligned left within the search input field
B Please bring the description text (Global Text Search (Reset): next to the search input field
C Make Both the search input field description text (Global Text Search (Reset) aligned center within its line

Preview how it should look
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/f67af34d-95c8-4145-b617-8f6cdda066d4)

**Comment by LeRatierBretonnien** [comment]
Like this ?

**Comment by LeRatierBretonnien** [comment]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/1085008/d48d1991-3349-409d-9772-8944687b6675)

**Comment by LeRatierBretonnien** [comment]
Fixed
