### ISSUE TITLE
Beneos Search Website: 18 - Search Tabs

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#66]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/627f7682-a3b8-41dd-b024-02c52004aa09)

1. To add a counter weight to the new Footer please change the top search tab bar (Tokens | Maps | Items | Spells) and change the bg Color the our red tone (`#3e0706`) and the text white (`#FFFFFF`)
2. Please Also change the text above to: `EXPLORE ALL BENEOS CONTENT - What are you looking for today?` and also change the color to (`#3e0706`)

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
