### ISSUE TITLE
Beneos Search Website: 19 - Search Form and Result Form hierarchy

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#67]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/fdad7b3c-6a50-4568-bdd8-515116a9d503)

Can you change the hierarchy of the Search form so the shadow of the search form falls on the result form and not the opposite around?

**Comment by LeRatierBretonnien** [comment]
Fixed in next release
