### ISSUE TITLE
Beneos Search Website: 20 - Footer 2

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#69]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/d59c8408-3d76-4be5-914a-bad3a976d24d)

1. Please make sure the Footer is always at the bottom of the screen
2. Make the Footer Transparency 66% (100% = fully visible, 0% = invisible)

**Comment by LeRatierBretonnien** [comment]
Changed
