### ISSUE TITLE
Database: Spell Adjustments

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#7]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3758d6cc-0159-4e39-aef3-06c625f99843)

In order to optimize user experience can you add following adjustments to the design?

1. Can you separate the description line visually from the rest? Maybe with a soft gray background to make the text not float in the nirvana? =)
2. Can you make the classes left aligned and add the text `Classes:` in front of the entries. For example "Classes: Warlock Cleric Sorcerer"
3. Can you please add two static text labels "Level" and "Spell" as well to make it a sentence? "Level 1 Conjuration Spell" 
4. On a mouseover, only the back card of the spell card is displayed, not the front side.

**Comment by LeRatierBretonnien** [comment]
All changes done
