### ISSUE TITLE
Beneos Search Website: 22 - Clickable Beneos Logo

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#71]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/bc261d41-81ab-45ed-bb75-9c3ea9007e68)

Just for ergonomy reasons can you add a link when clicking on the icon? Link: `https://www.patreon.com/BeneosBattlemaps`

**Comment by LeRatierBretonnien** [comment]
Fixed
