### ISSUE TITLE
Beneos Search Website Spells: 23 - "Bonus Action" is out of bound

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#72]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/3a2b412e-e468-42e5-8162-7d434c8846b4)

Can you make the term "Bonus Action" fit into the field?

**Comment by LeRatierBretonnien** [comment]
Font size reduction applied
