### ISSUE TITLE
Beneos Search Website Maps: 25 - Map Grid Filter should behave like the Item Price Filter

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#74]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/528726c5-ceff-4976-bb3f-b84ecd07158e)

The Map `Grid `filter should be renamed to `Size`
To determine the size of a map both values should be multiplied: AxB (A times B = **Size Value**). For examples 44x26 means this map has 1144 squares

Similar to the price of items there should be a range filter to determine the `size `of a map
-  **Size Value** < 150 = Tiny
-  **Size Value** < 500 = Small
-  **Size Value** <= 1000 = Medium
- **Size Value** <= 2000 = Big
- **Size Value** > 2000 = Very Big

**THIS SHOULD BE FOR BOTH, THE WEBSITE AND THE MODULE**

**Comment by LeRatierBretonnien** [comment]
Fixed
