### ISSUE TITLE
Beneos Search Website Tokens: 26 - CR ist not sorted incrementially

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#75]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/841b731f-51f9-45be-bbd9-858997c08b80)

The CR values are sorted alphabetically but should be sorted numerical (incrementially). That means `0.5 ... 1 ... 10 ... 11 ... 20 ... 21 ... 30`

**Comment by LeRatierBretonnien** [comment]
Fixed
