### ISSUE TITLE
Beneos Search Website Tokens: 27 - First Letter Upper case?

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#76]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/00a69dcc-185b-4a40-829e-41dcddd270bc)

Can you force the first letter of every Filter (for all: Maps, Tokens, Items and Spells) to be upper case, or do we need to change this in the database? Would it break something?

It is more appealing and readable if every word is with a capital letter at the beginning.

**Comment by LeRatierBretonnien** [comment]
Fixed
