### ISSUE TITLE
Beneos Search Website Maps: 28 - When switching to the Maps Tab the filters are set to "undefined"

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#77]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/d243e32d-0984-4f09-84de-d17dc0b2c9e7)

If you switch to maps, spells and items the filters are empty, Tokens has all filters set to "Any" as default. I do not know what behaviour is the intended one but one of them seems wrong.

Do the same for Spells, Items and Mapsplease

![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/4e09af05-f727-4181-bb41-f37c07e9f570)

![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/d3b31f3f-a752-4e61-aae8-420fba0adce9)

**Comment by LeRatierBretonnien** [comment]
Fixed
