### ISSUE TITLE
Beneos Search Website Tokens: 29 - It looks like "Token Type" does not filter correctly

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#78]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/27579928-a819-49fa-bef8-10db0e0d3dec)

When using token type the result is always empty, even though the token itself (Aberration for example), has the correct tag applied in the results

**Comment by LeRatierBretonnien** [comment]
Fixed
