### ISSUE TITLE
Beneos Search Website Map: 30 - Grid and Type has "Any" twice and needs to be renamed

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#79]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/99e12314-2faf-40e2-9e59-5d1793626568)

- As Mentioned in the other ticket, please rename `Grid `to `Map Size`
- Remove the redundant `Any` in **Type** and **Grid** (**Map Size**)

**Comment by LeRatierBretonnien** [comment]
Fixed
