### ISSUE TITLE
Beneos Search - Module: When using Text Search and delte the text the filter does not resets

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#82]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/1952aceb-2e4e-4737-8caa-2bcd941e3b7c)

Once you entered a text into the Global Text Search You canot "undo" it to go back to a "any" search when deleting the text

**Comment by LeRatierBretonnien** [comment]
Fixed
