### ISSUE TITLE
Beneos Search - Module + Website: Typo Biom -> Biome

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#83]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/190af27b-6652-47ca-9fcd-71bdd489b0e5)

Please correct this little Typo: Wrong: `Biom`, correct `Biome`

**Comment by LeRatierBretonnien** [comment]
Fixed
