### ISSUE TITLE
Beneos Module:  Death token at 0 HP is not working

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#84]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/221b04b0-67e7-4267-bee7-64717b818ee1)

When an actor reaches 0 HP ist should display an static imagice indicating thos token is "dead".

- When a Top Down Idle is active: Use `token_name \ top \ token_name-dead_top.webp`
- When an animated portrait is active: Use `token_name \ token_name-idle_face_still_death.webp`
- When an isometric animation is active - Do nothing.

**Comment by LeRatierBretonnien** [comment]
Should be OK now
