### ISSUE TITLE
Beneos Module: Text search for Token replacement throws error

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#88]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/55433c70-05f5-4a0c-911d-cbd3e9d39570)

When right clicking an anavat to change a token you can not use the text search. It throws this error

beneos_search_engine.js:37 Uncaught (in promise) TypeError: undefined. BeneosUtility.getBeneosModuleDataPath is not a function
[Detected 1 package: beneos_module]
    at BeneosModuleMenu.displayResults (beneos_search_engine.js:37:84)
    at BeneosModuleMenu.processTextSearch (beneos_search_engine.js:58:12)
    at beneos_search_engine.js:74:18
    
    Error Log:
[localhost-1696685034447.log](https://github.com/BeneosBattlemaps/beneos_module/files/12837885/localhost-1696685034447.log)

**Comment by LeRatierBretonnien** [comment]
Fixed
