### ISSUE TITLE
Beneos Module Search - "Import New Content" button hard to press

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#89]
https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/e0e8de09-6630-4553-aa00-7d85a1a4db9d

It looks like an invisible layer prevents you sometimes from cliccking the button

**Comment by LeRatierBretonnien** [comment]
Unable to reproduce, Firefox and Chrome
