### ISSUE TITLE
Beneos Search: Module - "Fitting Scenery" and "Fitting Battlemaps" are not needed anymore

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#91]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/86d59ec7-c3a4-4313-87b4-54f67b4585f9)

Because we display bith siblings in the tooltip we do not need that soltuion anymore and can safe space

**Comment by LeRatierBretonnien** [comment]
Fixed
