### ISSUE TITLE
Beneos Search: Module - Maps: Text behind the tag bar

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#93]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/6e541588-7f14-4b5b-b691-624859c8e7e7)

It seems there are tags behind the tag bar. Can you make the tag row to expand or stops displaying additional tags in case it would lead to a new line?

**Comment by LeRatierBretonnien** [comment]
Tags are clipped, fixed
