### ISSUE TITLE
Beneos Search Module - Maps - Grid/Size Sorting + Rename

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#95]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/d1ecfd5d-3c12-4d7d-ac64-0d21c77257b5)

**1. Can you make it not sort alphabetically but logically?**

1. Tiny
2. Small
3. Medium
4. Big
5. Very Big

2. Can you rename Grid to **Size** ?

**Comment by LeRatierBretonnien** [comment]
Fixed
