### ISSUE TITLE
Beneos Search Module - Maps - Additional "Any" Tags

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#96]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/2db210ea-aa23-49be-aa2e-8ba26007b258)

Foe Battlemaps we have additional Any tags even though there is no `"Any"` defined as tag in the `beneos_battlemaps_database.json`.

IT LOOKS LIKE ALL FILTERS HAVE THIS BEHAVIOUR in addition to any "Any" tags that are defined in the jsons

**Comment by LeRatierBretonnien** [comment]
Fixed
