### ISSUE TITLE
Beneos Search Website + Module: Token CR Spectrums

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#97]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/b90af77b-c44c-4d77-8e5c-9e78b7297c2c)

Because you already did spectrums (ranges) for maps and items I would like to use this for tokens as well. Instead of clicking through all CRs it would be way more usable if we'd define ranges here as well.

0.25 to 4 -> Text: `0 to 4`
5 to 10    -> Text: `5 to 10`
11 to 15  -> Text: `11 to 15`
15 to 30  -> Text: `15+`

**Comment by LeRatierBretonnien** [comment]
Changed, new feature
