### ISSUE TITLE
Beneos Search - Module Spells: "Bonus Action" text out of bound

### ISSUE THREAD

**Issue by BeneosBattlemaps** [BeneosBattlemaps/beneos_module#99]
![image](https://github.com/BeneosBattlemaps/beneos_module/assets/93905181/d4c79863-d2cf-46dc-9b0d-0a3a39bbb074)

Same as we had on our website. `Bonus Action` is a bit too big and creates a new line.

**Comment by LeRatierBretonnien** [comment]
Fixed
